# Generated by Django 5.1 on 2024-08-31 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quiz', '0009_academicyear_enddate_academicyear_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('academic_yr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.academicyear')),
                ('class_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.classlist')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
