# Generated by Django 5.1 on 2024-08-10 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_remove_quizmaster_classid_quizmaster_classlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accYear', models.CharField(max_length=4)),
                ('desc', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'academic_year',
            },
        ),
        migrations.AddField(
            model_name='quizmaster',
            name='acc_year',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, to='Quiz.academicyear'),
            preserve_default=False,
        ),
    ]
