# Generated by Django 5.1 on 2024-08-15 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_academicyear_quizmaster_acc_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
