# Generated by Django 5.0.6 on 2024-09-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cultural_events', '0001_initial'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudeEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgm_id', models.IntegerField()),
                ('description', models.CharField(max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cultural_events.events_master')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.students')),
            ],
            options={
                'db_table': 'student_events',
            },
        ),
    ]
