# Generated by Django 5.0.6 on 2024-09-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cultural_events', '0001_initial'),
        ('Students', '0001_initial'),
        ('studevents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudeEvents',
            new_name='StudEvents',
        ),
    ]
