# Generated by Django 5.0.6 on 2024-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
        ('studevents', '0003_compstudevents_delete_studevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compstudevents',
            name='student',
        ),
        migrations.AddField(
            model_name='compstudevents',
            name='student',
            field=models.ManyToManyField(to='Students.students'),
        ),
    ]
