# Generated by Django 5.0.6 on 2024-09-29 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
        ('studevents', '0004_remove_compstudevents_student_compstudevents_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compstudevents',
            name='student',
        ),
        migrations.AddField(
            model_name='compstudevents',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.students'),
        ),
    ]
