# Generated by Django 5.0.6 on 2024-10-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_academicyear_enddate_academicyear_startdate'),
        ('studevents', '0005_remove_compstudevents_student_compstudevents_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='compstudevents',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.classlist'),
        ),
    ]
