# Generated by Django 5.0.6 on 2024-10-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cultural_events', '0001_initial'),
        ('studevents', '0007_formtest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formtest',
            old_name='standard',
            new_name='Standard',
        ),
        migrations.AddField(
            model_name='formtest',
            name='Event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cultural_events.events_master'),
        ),
    ]
