# Generated by Django 5.0.6 on 2024-10-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
        ('studevents', '0008_rename_standard_formtest_standard_formtest_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtest',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.students'),
        ),
    ]
