# Generated by Django 5.1 on 2024-10-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studevents', '0009_formtest_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='compstudevents',
            name='prize',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
