# Generated by Django 5.0.6 on 2024-08-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('competition_item', models.CharField(default='N', max_length=1)),
                ('group_item', models.CharField(default='N', max_length=1)),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'events_master',
            },
        ),
    ]
