# Generated by Django 5.1 on 2024-10-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cultural_events', '0002_culturalevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalevents',
            name='EventOrder',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='culturalevents',
            name='FileName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
