# Generated by Django 5.1 on 2024-10-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cultural_events', '0003_culturalevents_eventorder_culturalevents_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalevents',
            name='EventOrder',
            field=models.IntegerField(null=True),
        ),
    ]
