# Generated by Django 5.1 on 2024-10-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cultural_events', '0004_alter_culturalevents_eventorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_master',
            name='artistic_item',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='events_master',
            name='sports_item',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
