# Generated by Django 5.1 on 2024-10-21 14:08

import Cultural_events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cultural_events', '0005_events_master_artistic_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalevents',
            name='EventDesc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='culturalevents',
            name='EventFile',
            field=models.FileField(null=True, upload_to=Cultural_events.models.CulturalEvents.upload_path),
        ),
    ]
